language: ruby

rvm:
  - 1.8.7
  - 1.9.3

script:
  - bundle exec rake spec
  - bundle exec rake lint
  - bundle exec rake validate

env:
  - PUPPET_VERSION="2.7.0"
  - PUPPET_VERSION="3.1.0"
  - PUPPET_VERSION="3.2.0"
  - PUPPET_VERSION="3.4.0"
  - PUPPET_VERSION="3.6.0"

gemfile: .gemfile
